# Generated by Django 3.2.13 on 2022-06-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'Целое число'), (2, 'Вещественное число'), (3, 'Текст'), (4, 'Да/нет'), (5, 'Дата и время'), (6, 'Дата'), (7, 'Время')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Неизвестный тип', max_length=40, unique=True)),
                ('feature_types', models.ManyToManyField(to='item.FeatureType')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=5000)),
                ('ranking', models.PositiveSmallIntegerField(default=0)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='item.item')),
            ],
        ),
    ]
