# Generated by Django 3.2.13 on 2022-06-15 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfeedback',
            name='item_id',
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='item.itemtype'),
        ),
        migrations.AddField(
            model_name='itemfeedback',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', related_query_name='feedback', to='item.item'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='feature_types',
            field=models.ManyToManyField(related_name='item_types', related_query_name='item_type', to='item.FeatureType'),
        ),
        migrations.CreateModel(
            name='ItemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=64)),
                ('feature_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='item.featuretype')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', related_query_name='feature', to='item.item')),
            ],
        ),
    ]
